import { Providers } from '@/components'
import './globals.css'

export const metadata = {
  title: 'My ChatApp',
  description: 'Realtime chat app generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
